### ISSUE TITLE
perfdhcp should be able to specify extra options (trac5554)

### ISSUE THREAD

**Issue by tomaszmrugalski** [isc-projects/kea#77]
We're debugging an issue with customer's setup. It would be very useful for the perfdhcp to be able to specify extra options.

Original report: https://kea.isc.org/ticket/5554

**Comment by tmarkwalder** [comment]
I fixed up the doc wording a little and added usage text for the command line argument.   Pull first, if you agree, please merge.

**Comment by tomaszmrugalski** [comment]
The code is now merged. Closing issue.
