### ISSUE TITLE
Extend host structure to hold keys

### ISSUE THREAD

**Issue by tomaszmrugalski** [isc-projects/kea#83]
As part of the IPv6 reconfigure implementation, we need to store reconfigure keys for hosts. Host structure needs to be extended to store keys.

General rules apply: the code has to be well documented, there have to be unit-tests.

It's worth reading the [contributor's guide](https://jenkins.isc.org/job/Kea_doc/doxygen/d7/df4/contributorGuide.html). Once the code is done, please send a PR (pull request).

**Comment by MayyaSunil** [comment]
Along with keys, we need to store IP address and interface name for sending a unicast reconfigure message to the client.(Or any other way to figure which interface and address the client is connected on ?)
Support to store and retrieve from database backends is being added as well.

**Comment by tomaszmrugalski** [comment]
The AuthKey class is on master for a long time and will be released in 1.5.0 tomorrow.
