### ISSUE TITLE
Implement Authentication options in DHCPv6 messages

### ISSUE THREAD

**Issue by MayyaSunil** [isc-projects/kea#86]
Implement authentication option in DHCPv6 message to support RKAP. This issue is needed to implement the reconfiguration mechanism.

**Comment by tomaszmrugalski** [comment]
The src/lib/dhcp/option6_auth.cc|h are now on master. This code will be released in 1.5.0. Closing.

Sunil, thanks for your contributions. We haven't managed to put all the code in 1.5.0, but once it's released (hopefully tomorrow), we can revive this work and finish up remaining code. In the coming days I'll be moving the code over from github to gitlab.
