### ISSUE TITLE
Time of issue of ip address

### ISSUE THREAD

**Issue by PBA4** [isc-projects/kea#90]
It is not possible to issue a permanent ip address to the user. In the RFC, it is said that the leases-time can be set to -1, thereby reserving the IP address of the user by the user, but this does not work and kea talks about the error. I store ip addresses in the mysql. How can I make the addresses reserved after the issue?

**Comment by vrisk** [comment]
Hello there PBA4. This is really not the best place to post questions. If you are still looking for an answer, try joining and emailing dhcp-users@lists.isc.org. However, just to preserve the report, I have migrated this issue to our new issue tracker at: https://gitlab.isc.org/isc-projects/kea/issues/322.
