### ISSUE TITLE
Make it possible to start the server without all the configured interfaces ready

### ISSUE THREAD

**Issue by karaluh** [isc-projects/kea#91]
Dibbler has an "inactive-mode" option, which works like this, according to the official docs:

> During normal startup, client tries to bind all interfaces defined in a configuration file. If such attempt
fails, client reports an error and gives up. Usually that is best action. However, in some cases it is possible that interface is not ready yet, e.g. WLAN interface did not complete association. Dibbler attempt to detect link-local addresses, bind any sockets or initiate any kind of communication will fail. To work around this disadvantage, a new mode has been introduced in the 0.6.0RC4 version. It is possible to modify client behavior, so it will accept downed and not running interfaces. To do so, inactive-mode
keyword must be added to client.conf file. In this mode, client will accept inactive interfaces, will add
them to inactive list and will periodically monitor its state. When the interface finally goes on-line, client
will try to configure it."

My use case is PD over PPP interfaces which come and go as they please during the server process lifetime and mostly aren't there when the server starts.

**Comment by vrisk** [comment]
Hello!  I am very sorry we haven't replied yet to this request. We are consolidating our issue trackers so that we can do better in triaging new issues. This issue has been moved to our primary repo, at https://gitlab.isc.org/isc-projects/kea/issues/321.  Please follow it there.

Again, thank you for the feature request.
