### ISSUE TITLE
Request for REST API info. On release related CRUD actions.

### ISSUE THREAD

**Issue by larssb** [isc-projects/kea#92]
I'm politely requesting info on how the hooks, for managing releases and the like, via the REST API works (if possible at all). I read about them here [Kea-1.4-release-notes](https://kea.isc.org/wiki/KeaReleaseNotes140) and in greater detail here [Lease-cmds](https://kea.isc.org/docs/kea-guide.html#lease-cmds).
Do one have to call these cmds directly or is it possible to e.g. via cURL or the like request an API endpoint and get Kea to invoke code resembling the functionality of one of the lease-cmds. 

I'm asking as I'm strongly considering using Kea for DHCP and I'm eager to use PowerShell and the cmdlets for REST API interaction for administering Kea itself and the available release management actions. An example of a PowerShell cmdlet could be [Invoke-WebRequest](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-6).

Is this possible? Or would I have to invoke these commands on the cmdline and the try to marhall the returned output into objects and work it out from there?

I hope I have made myself clear in the above. If not feel free to ask for additional details.

Thank you very much and I'm looking forward to your response.

**Comment by fxdupont** [comment]
Perhaps the Kea control agent is waht you are looking for?

Regards

Francis Dupont <fdupont@isc.org>

**Comment by tomaszmrugalski** [comment]
Have you looked at [Kea 1.4 User's Guide](https://kea.isc.org/docs/kea-guide.html#kea-ctrl-agent), especially Section 7 - Control Agent - this piece exposes the REST API over http(s), Section 16 that explains how the API works in general and Section 14.4.5 that explains lease command in detail.

You may also keep an eye out for [ticket #5422](https://kea.isc.org/ticket/5422). It will introduce a reference to all Kea commands. The information is already mostly there in the User's guide, but currently it is a bit scattered around the whole document.

**Comment by vrisk** [comment]
Hello larssb,

I hope you have found a good way to communicate with Kea by now. I am not sure if the commits above relate to issue #92 here, or issue #92 in Gitlab, our primary repo... As Tomek mentions, we have created a section in the User Guide that collects all the API commands.   If you want to reopen this issue or comment further, please go to our new repo, where this is https://gitlab.isc.org/isc-projects/kea/issues/324.  We are closing the issue tracker here on Github and consolidating to the gitlab.isc.org site. 

Thank you!
