### ISSUE TITLE
REST API health endpoint

### ISSUE THREAD

**Issue by Smithx10** [isc-projects/kea#96]
**Describe the solution you'd like**
A Health Endpoint via the REST API that informs the user if the Kea Services are healthy and serving.
ex: localhost:8080/health

Would respond  with a JSON object with some brief information about the KEA services running on the server and their health status.

**Describe alternatives you've considered**
```
status=keactrl status | grep "DHCPv4 server" | awk '{print $3}'
if [[ "${status}" == "active" ]] then;
  _log "DHCP is healthy"
  return 0
else 
  _log "DHCPv4 is not healthy"
  return 1 
fi
```

**Comment by vrisk** [comment]
This issue was migrated to our new working repository at https://gitlab.isc.org/isc-projects/kea/issues/318.  Please go there to report any followup or discuss further.
We are closing this issue tracker because we simply can't monitor multiple issue streams. 
Thank  you!
